#pragma once
#include <io_system/sched/file/details/system_sched/\iosys_sched_system_type.h>
#include <stdbool.h>

__synapse_iosys_sched_system_io_request*
__synapse_iosys_sched_system_io_request_initialize
	(void*, size_t, size_t);

void
__synapse_iosys_sched_system_io_request_cleanup
	(__synapse_iosys_sched_system_io_request*);

void
__synapse_iosys_sched_system_io_request_dispatch_read
	(__synapse_iosys_sched_system_io_session*, __synapse_iosys_sched_system_io_request*);

void
__synapse_iosys_sched_system_io_request_dispatch_write
	(__synapse_iosys_sched_system_io_session*, __synapse_iosys_sched_system_io_request*);

__synapse_iosys_sched_system_io_request*
__synapse_iosys_sched_system_io_request_retrive_completed  
	(__synapse_iosys_sched_system*);

__synapse_iosys_sched_system_io_request*
__synapse_iosys_sched_system_io_request_retrieve_completed_until
	(__synapse_iosys_sched_system*, uint64_t);

bool
__synapse_iosys_sched_system_io_request_wait
	(__synapse_iosys_sched_system_io_request*);

bool
__synapse_iosys_sched_system_io_request_wait_until
	(__synapse_iosys_sched_system_io_request*, uint32_t);